name: trial
description: "A new Flutter project."

# Prevents the package from being accidentally published to pub.dev
publish_to: 'none' # Remove this line if you want to publish to pub.dev

# Defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0" # Ensure that the SDK version fits your Flutter version

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.0  # Correct placement under dependencies
  table_calendar: ^3.0.3
  cupertino_icons: ^1.0.8  # Cupertino icons dependency

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/